### ISSUE TITLE
运行时报错：TypeError

### ISSUE THREAD

**Issue by OneTrueSum95** [initialencounter/koishi-plugin-open-vits#1]
C:\AI\koishi-plugin-open-vits>node -r esbuild-register .
C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:336
  if (typeof data !== 'string') throw new TypeError(`expected string but got ${data}`)
                                ^

TypeError: expected string but got 3
    at <anonymous> (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:336:39)
    at Function.resolve (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:273:24)
    at property (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:386:35)
    at <anonymous> (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:434:19)
    at Function.resolve (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:273:24)
    at schema (C:\AI\koishi-plugin-open-vits\node_modules\schemastery\src\index.ts:104:19)
    at resolveConfig (C:\AI\koishi-plugin-open-vits\node_modules\cordis\src\utils.ts:19:54)
    at Registry.plugin (C:\AI\koishi-plugin-open-vits\node_modules\cordis\src\registry.ts:100 :14)
    at Context.plugin (C:\AI\koishi-plugin-open-vits\node_modules\cordis\src\context.ts:78:30)
    at Context.import_core.Context.plugin (C:\AI\koishi-plugin-open-vits\node_modules\koishi\src\index.ts:39:17)

Node.js v18.16.0

系统：window10
python版本：3.9.13

**Comment by initialencounter** [comment]
配置项忘记改了。。，把配置项改成这样应该就可以了
<img width="493" alt="截屏2023-06-09 22 37 05" src="https://github.com/initialencounter/koishi-plugin-open-vits/assets/109729945/ba2b1c19-e816-4f37-b0af-07fdfcd5a717">

或者 git pull 一下

**Comment by initialencounter** [comment]
配置项忘记改了。。，把配置项改成这样应该就可以了
<img width="403" alt="截屏2023-06-09 22 24 46" src="https://github.com/initialencounter/koishi-plugin-open-vits/assets/109729945/3285b6d0-112a-494a-98a1-ba6017707868">
