### ISSUE TITLE
能否直接发语音

### ISSUE THREAD

**Issue by copurxia** [initialencounter/koishi-plugin-open-vits#6]
```
Error: Error with request send_group_msg
```
现在在onebot平台会报这个，其他平台倒是能正常

**Comment by initialencounter** [comment]
修改语音格式试试

**Comment by copurxia** [comment]
四个格式都不行

**Comment by initialencounter** [comment]
请提供详细的报错信息，以及平台信息，插件配置信息，版本信息

**Comment by copurxia** [comment]
```bash
session Error: Error with request send_group_msg, args: {"group_id":"739498411","message":[{"type":"record","data":{"file":"base64://T2dnUwACAAAAAAAAAADUHZAGAAAAAGKHTl4BHgF2b3JiaXMAAAAAASJWAAAAAAAAN7AAAAAAAACpAU9nZ1MAAAAAAAAAAAAA1B2QBgEAAABna8khDlr////////////////FA3ZvcmJpczQAAABYaXBoLk9yZyBsaWJWb3JiaXMgSSAyMDIwMDcwNCAoUmVkdWNpbmcgRW52aXJvbm1lbnQpAQAAABIAAABFTkNPREVSPWxpYnNuZGZpbGUBBXZvcmJpcyJCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xzoxhXzHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1JyrjXnnHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xzIDRkFQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy67ouEBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP8zzP8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQAABhFDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQri...
                            at _Internal._get (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:118:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:149:20)
                            at async _OneBotMessageEncoder.flush (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:744:159)
                            at async _OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:509:5)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2327:7
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2189:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:844:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:844:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:844:16)
```
open-vits版本：1.6.2
onebot版本：6.0.1
go-cq版本：3.8.0
均为koishi官方市场下载
平台是运行在j3455上的docker
```yaml
open-vits:yjniio:
endpoint: http://172.18.0.8:23456
lang: auto
```

**Comment by copurxia** [comment]
给45了，先换成Chronocat了
